name              'fastly'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Resources for Configuring Fastly Services'
version           '0.6.16'
source_url        'https://github.com/sous-chefs/fastly'
issues_url        'https://github.com/sous-chefs/fastly/issues'
chef_version      '>= 16.0'

supports 'any'
