name             'fastly'
maintainer       'Corporate Infrastructure and Security - Chef Software, Inc.'
maintainer_email 'cia@chef.io'
license          'Apache-2.0'
description      'Resources for Configuring Fastly Services'
version          '0.5.0'
source_url       'https://github.com/chef-cookbooks/fastly'
issues_url       'https://github.com/chef-cookbooks/fastly/issues'
gem              'fastly'
supports         'any'
chef_version     '>= 12.10'
