source 'https://supermarket.chef.io'

metadata

cookbook 'delivery-truck', git: 'https://github.com/chef-cookbooks/delivery-truck.git'
cookbook 'delivery-sugar', github: 'chef-cookbooks/delivery-sugar'
cookbook 'chef_slack', git: 'https://github.com/chef-cookbooks/chef_slack.git'
